In [3]:
import numpy as np
sentence = """Thomas Jefferson began building Monticello at the age of 26.""" 
sentence.split()

['Thomas',
 'Jefferson',
 'began',
 'building',
 'Monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [4]:
token_sequence = str.split(sentence)

In [5]:
vocab = sorted(set(token_sequence)) 

# What is the difference between vocab and the output of sentence.split().

In [6]:
print(vocab)

['26.', 'Jefferson', 'Monticello', 'Thomas', 'age', 'at', 'began', 'building', 'of', 'the']


# why 26. ? What does it mean? is it a floting point number or age.?

In [7]:
', '.join(vocab)

'26., Jefferson, Monticello, Thomas, age, at, began, building, of, the'

In [8]:
num_tokens = len(token_sequence)
print(num_tokens)

10


In [9]:
vocab_size = len(vocab)
print(vocab_size)

10


In [10]:
onehot_vectors = np.zeros((num_tokens,vocab_size), int)
print(onehot_vectors)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [11]:
for i, word in enumerate(token_sequence):
    onehot_vectors[i,vocab.index(word)]=1

In [12]:
onehot_vectors

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
' '.join(vocab)

'26. Jefferson Monticello Thomas age at began building of the'

In [14]:
onehot_vectors

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
l = ["eat", "sleep", "repeat"]

In [16]:
print (list(enumerate(l)))
print (list(enumerate(l, 5)))

[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(5, 'eat'), (6, 'sleep'), (7, 'repeat')]


In [17]:
for count, ele in enumerate(l):
    print (ele,count)

eat 0
sleep 1
repeat 2


# Improving readability using pandas dataframes which convert 1D arrays in to series of lists, dictionaries and numbers of tables with labels

In [24]:
import pandas as pd
df = pd.DataFrame(onehot_vectors, columns = vocab)

In [25]:
#df[df==0] = ''

In [26]:
df

26.  Jefferson  Monticello  Thomas  age  at  began  building  of  the
0    0          0           0       1    0   0      0         0   0    0
1    0          1           0       0    0   0      0         0   0    0
2    0          0           0       0    0   0      1         0   0    0
3    0          0           0       0    0   0      0         1   0    0
4    0          0           1       0    0   0      0         0   0    0
5    0          0           0       0    0   1      0         0   0    0
6    0          0           0       0    0   0      0         0   0    1
7    0          0           0       0    1   0      0         0   0    0
8    0          0           0       0    0   0      0         0   1    0
9    1          0           0       0    0   0      0         0   0    0

# Each Row represents a vector for a single word and all UNIQUE for 10 Words
# Each column represents a word in your corpus. words in the document.
# Location of '1' in a column indicates a vocabulary word that was present at the position in the sentence or document.
# Check the above statemet,..
# ALL BUT ONE - One-Hot - 1

In [34]:
s = df.iloc[2]
print(s)

26.           0
Jefferson     0
Monticello    0
Thomas        0
age           0
at            0
began         1
building      0
of            0
the           0
Name: 2, dtype: int32


# Number representation for the word 'Began' as a vector

# One Hot encoding vectors retain all the details such as word order, grammar and order of the original sentence

# suppose there is corpus of 3000 books with 3500 sentences and 15 words per sentence.
# Calculate the size of the one-hot encoding vector.

In [36]:
num_rows = 3000*3500*15
print(num_rows)

157500000


In [43]:
num_bytes = num_rows * 1000000
print(num_bytes/1e12)
print('Tera Bytes')

157.5
Tera Bytes


# Not a good way of representation